fun main() {
    var fila : Enfileiravel = FilaEstatica()
    fila.enfileirar("A")
    println("Espiar: ${fila.espiar()}")
    fila.enfileirar("B")
    fila.enfileirar("C")
    fila.enfileirar("D")
    fila.desenfileirar()
    fila.enfileirar("E")
    fila.enfileirar("F")
    val conteudo = fila.desenfileirar()
    println("Espiar: ${fila.espiar()}")
    fila.enfileirar("G")
    fila.enfileirar(conteudo)
    fila.enfileirar("I")
    fila.enfileirar("J")
    fila.enfileirar("K")
    println("Fila=${fila.imprimir()}")
}